### ISSUE TITLE
wdb/errors.h file not found

### ISSUE THREAD

**Issue by dobrerazvan** [metno/wdb-netcdfload#1]
Hi

I think 4db8086848fd1a4be26be410c6c0e3ae573965fe does not use the respective feature in wdb. Errors.h file is not present in wdb source tree.

Thanks.

**Comment by michaeloa** [comment]
Hi,

Thanks for getting in touch. We maintain the bug database for all things WDB related at http://phab.met.no now. 

This issue has been moved there under https://phab.met.no/T900 (login required to post).

Regards,

Michael A.
